name: Build

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019]
    steps:
      - uses: actions/checkout@v2
    
      - name: Install Qt
        uses: jurplel/install-qt-action@v2

      - name: Build on Windows
        if: startsWith(matrix.os, 'windows')
        run: |
          qmake
          make
          ls -l
        shell: cmd
          
      - name: Build on Linux
        if: (!startsWith(matrix.os, 'windows'))
        run: |
          qmake
          make
          dir
        shell: bash
