name: Build

on: push

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
  
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
          
      - name: Build
        run: |
          qmake
          make
        shell: bash
        
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: Build-Lin
          path: ./FlaxPlugMan
          
  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
  
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          arch: win64_msvc2015_64
          
      - name: Build
        run: |
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          qmake
          make
        shell: cmd
        
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: Build-Win
          path: release/FlaxPlugMan.exe
